accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import CreateCheckoutSessionView

app_name="accounts"

urlpatterns = [
    path('',views.indexpage,name="indexpage"),
    path('homepage/',views.homepage,name="homepage"),
    path('signup/',views.sign_up,name="sign-up"),
    path('login/',views.log_in,name="log-in"),
    path('logout/',views.log_out,name="log-out"),


    path('category/<str:category_name>',views.category_filter,name='filter'),
    path('checkout/<int:id>',views.checkout,name='checkout'),
    path('myorders/',views.my_orders,name="my-orders"),
    path('cancel-order/<int:id>',views.cancel_order,name="cancel-order"),
    path('prediction/',views.prediction,name="prediction"),
    path('analyze',views.analyze,name="analyze"),
    path('messages/',views.messages,name="messages"),

    path('landing-page/',views.landing_page,name="landing-page"),
    path('create-checkout-session/<int:id>',CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('payment-successfull/',views.payment_successfull,name='payment-successfull'),
    path('payment-cancelled/',views.payment_cancelled,name='payment-cancelled')

    

]

admin/urls.py
from django.contrib import admin
from django.urls import path
from .views import admin_views,product_views

app_name="admin"

urlpatterns = [
    path('',admin_views.dashboard,name='dashboard'),
    path('update',admin_views.update_profile,name='update-profile'),
    path('user-list',admin_views.user_list,name='user-list'),
    
    path('add-cake',product_views.add_cake,name='add-cake'),
    path('update-cake/<int:id>',product_views.update_cake,name='update-cake'),
    path('delete-cake/<int:id>',product_views.delete_cake,name='delete-cake')

]

cakebakery/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('accounts.urls')),
    path('admin/',include('admin.urls')),
   

]   + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length = 32)
    first_name = forms.CharField(max_length=32)
    last_name=forms.CharField(max_length=32)
    email=forms.EmailField(max_length=64)
    password1=forms.CharField()
    password2=forms.CharField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email',)

accounts/views.py
from django.shortcuts import render,reverse,redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages as mssg
from products.models import cake_list,orders,messages
from .forms import SignUpForm
from products.forms import make_order_form,message_form
import pandas as pd   
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


# Create your views here.

def indexpage(request):
    context = dict()
    context['title'] = 'indexpage'
    return render(request,'accounts/index.html',context)

def homepage(request):
    context = dict()
    items = cake_list.objects.all()
    context['items'] = items
    return render(request,'accounts/homepage.html',context)

def category_filter(request,category_name):
    context = dict()
    items = cake_list.objects.filter(category = category_name)
    context['items'] = items
    return render(request,'accounts/homepage.html',context)

def sign_up(request):
    form = SignUpForm(request.POST or None)
    context= dict()
    context["form"] = form
    if request.method == "POST":
        if form.is_valid(): 
            user=form.save()
            login(request,user)      
            return redirect(reverse('accounts:homepage'))
        else:
            mssg.info(request,form.errors)
            return render(request,'accounts/sign_up.html',context)
    return render(request,'accounts/sign_up.html',context)

def log_in(request):
    form = AuthenticationForm(request, data=request.POST)
    context= dict()
    context["form"] = form
    if request.method == "POST":
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username = username,password=password)
            login(request,user)  
            if user.is_superuser:
                return redirect(reverse('admin:dashboard'))
            if user:    
                return redirect(reverse('accounts:homepage'))
        else:
            return render(request,'accounts/log_in.html',context)    
    return render(request,'accounts/log_in.html',context)

def log_out(request):
    logout(request)
    return redirect(reverse('accounts:log-in'))

def my_orders(request):
    context = dict()
    user = request.user
    myorders = orders.objects.filter(user_id = user.id).order_by('-date')
    context['orders'] = myorders
    return render(request,'accounts/my_orders.html',context)

def cancel_order(request,id):
    order = orders.objects.get(id = id)
    order.order_status = 'Cancelled'
    order.save()
    mssg.info(request,'Order cancelled successfully. Refund will be credited to your bank account within 3-4 working days')
    return redirect(reverse('accounts:my-orders'))

def prediction(request):
    return render(request, 'accounts/prediction.html')

def analyze(request):
    crop = pd.read_csv("dataset/Crop_recommendation.csv")

    # remove duplicate values
    crop.drop_duplicates()

    # handle null values in dataset
    attr=["N","P","K","temperature","humidity","rainfall","label"]
    if crop.isna().any().sum() !=0:
        for i in range(len(attr)):
            crop[atrr[i]].fillna(0.0, inplace = True)

    #Remove unwanted parts from strings in a column 
    crop.columns = crop.columns.str.replace(' ', '') 

    # we have given 7 features to the algorithm
    features = crop[['N', 'P','K','temperature', 'humidity', 'ph', 'rainfall']]

    # dependent variable is crop
    target = crop['label']

    # our model will contain training and testing data
    x_train, x_test, y_train, y_test = train_test_split(features,target,test_size = 0.2,random_state =2)
    
    # here n_estimators is The number of trees in the forest.
    # random_state is for controlling  the randomness of the bootstrapping
    RF = RandomForestClassifier(n_estimators=20, random_state=0)

    # we'll use rf.fit to build a forest of trees from the training set (X, y).
    RF.fit(x_train,y_train)
    # at this stage our algorithm is trained and ready to use
    
    # take values from user
    N = request.POST.get('nitrogen', 'default')
    P = request.POST.get('phosphorous', 'default')
    K = request.POST.get('potassium', 'default')
    temp = request.POST.get('temperature', 'default')
    humidity = request.POST.get('humidity', 'default')
    ph =request.POST.get('ph', 'default')
    rainfall = request.POST.get('rainfall', 'default')

    # make a list of user input
    userInput = [N, P, K, temp, humidity, ph, rainfall]
    
    # use trained model to predict the data based on user input
    result = RF.predict([userInput])[0]

    # display  result to the user
    params = {'purpose':'Predicted Crop: ', 'analyzed_text': result.upper()}
    return render(request, 'accounts/analyze.html', params)    
    

def messages(request):
    context = dict()
    form = message_form(request.POST or None)
    context['form'] = form
    if request.method == "POST":
        if form.is_valid: 
            order=form.save()
            mssg.info(request,'Thank you for filling the form. Will get back to you soon')
    return render(request,'accounts/messages.html',context)

def checkout(request,id):
    context = dict()
    customer=request.user
    form = make_order_form(request.POST or None)
    context['customer'] = customer
    context['form'] = form
    if request.method == "POST":
        if form.is_valid: 
            order=form.save(commit = False)    
            order.user_id = customer.id
            order.cake_list_id = id
            order = order.save()
            context['id'] = id
            return render(request,'accounts/landingpage.html',context)
    return render(request,'accounts/delivery_details.html',context)

def landing_page(request):
    return render(request,'accounts/landingpage.html')

def payment_cancelled(request):
    cancel_order = orders.objects.latest('id')
    if cancel_order.status == 'Pending':
        cancel_order.delete()
    return redirect(reverse('accounts:homepage'))

def payment_successfull(request):
    success_order = orders.objects.latest('id')
    success_order.status = 'Success'
    success_order.save()
    return redirect(reverse('accounts:my-orders'))

accounts/templates/accounts/analyze.html
{% extends 'accounts/components/base.html' %}


{% block content %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<style>

      div.container{border-style: double;
      background-image: url("https://thumbs.dreamstime.com/b/rice-farm-blur-background-drop-bamboo-hut-rice-farm-blur-background-drop-water-rain-bamboo-hut-easy-life-123117043.jpg");}
  
      div.friend2field{
        font-weight: bold;
        display: grid;
        grid-template-columns: 1fr 3fr;
      }
      body {
        background-image: url('https://images.unsplash.com/photo-1625246333195-78d9c38ad449?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80');
      }
  
      .btn{
        float:right;
        font-weight: bold;
        border: 5px solid #555555;
  
  
  
      }
  
    
      </style>
    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>Geo Flora Prediction</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Geo Flora Prediction</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="about_us">About Us</a>
      </li>

    </ul>
  </div>
 
</nav>
-->
<section class="mbr-gallery cid-rbaMy1tJOl" once="shops" id="shop6-2" data-sortbtn="btn-primary">
  <div>
      <div class="mbr-shop" shop__showsidebar="">
        
          <div class="row col-md-12">
              <div class="col-xl-2 sidebar">
                {% include 'accounts/components/sidebar.html' %}
              </div>
              <!--<div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Success!</strong> Crop Has been predicted successfully!!!
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
            -->


              <div class="container">
                <div class="container">
                  <div
                    <h2 class="mbr-fonts-style mbr-section-title align-center display-2">Success! Crop Has Been Predicted Successfully!!!</h2>
                  </div>
                  <br>

                <h3>Your Predicted Crop -  </h3>
                <h1>
                  <pre>{{ analyzed_text }}</pre>
                </h1>
              </div>


                  <!-- Optional JavaScript -->
                  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
                  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
                  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
                </body>
              </html>
{% endblock %}

accounts/templates/accounts/homepage.html
{% extends 'accounts/components/base.html' %}
{% load static %}
{% block content %}

<section class="mbr-gallery cid-rbaMy1tJOl" once="shops" id="shop6-2" data-sortbtn="btn-primary">
    <div>
        <div class="mbr-shop" shop__showsidebar="">
            <!-- Shop Gallery -->
            <div class="row col-md-12">
                <div class="col-xl-2 sidebar">
                    {% include 'accounts/components/sidebar.html' %}
                </div>
                <div class="wrapper-shop-items col-xl-10">
                    <div class="mbr-gallery-row">
                        <div>
                            <div class="shop-items">
                                
                                    {% for item in items %}

                                    <div class="mbr-gallery-item">
                                        <div class="item_overlay" data-toggle="modal"></div>
                                        <div class="galleryItem" data-toggle="modal">
                                            <div class="style_overlay"></div>
                                            <div class="img_wraper">
                                                <img src="/media/{{item.image}}" alt="image">
                                            </div>
                                            <div class="sidebar_wraper">
                                                <h4 class="item-title mbr-fonts-style mbr-text display-5">
                                                    {{item.name}}
                                                </h4>
                                                <div class="price-block">
                                                    <span class="shop-item-price mbr-fonts-style display-5">
                                                        ₹ {{item.price}}
                                                    </span>
                                                </div>
                                                <div class="card-description">
                                                    {{item.description}}.&nbsp;
                    
                                                </div>
                                                <div class="mbr-section-btn" buttons="0" style="display: none;">
                                                    <a href="{% url 'accounts:checkout' item.id %}"
                                                        class="btn btn-secondary display-7">
                                                        Buy now!
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {% endfor %}

                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </div><!-- Lightbox -->
                <div class="shopItemsModal_wraper" style="z-index: 100;">
                    <div class="shopItemsModalBg"></div>
                    <div class="shopItemsModal row">
                        <div class="col-md-6 image-modal"></div>
                        <div class="col-md-6 text-modal"></div>
                        <div class="closeModal">
                            <div class="close-modal-wrapper"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</section>
{% endblock %}

accounts/templates/accounts/landingpage.html
{% extends 'accounts/components/base.html' %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>

<head>
  <title>Buy farming product</title>
  <link rel="stylesheet" href="style.css">
  <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
  <script src="https://js.stripe.com/v3/"></script>
</head>

<body>
  <section class="mbr-gallery cid-rbaMy1tJOl" once="shops" id="shop6-2" data-sortbtn="btn-primary">
    <div>
      <div class="mbr-shop" shop__showsidebar="">

        <div class="row col-md-12">
          <div class="col-xl-2 sidebar">
            {% include 'accounts/components/sidebar.html' %}
          </div>
          <div class="col-xl-1"></div>
          <div class="wrapper-shop-items col-xl-7">
            <h4>Please do not close the tab before completing the payment</h4>
            <h6>After clicking on proceed button, please wait for a few seconds...</h6>
            <div>
              <button class="btn btn-success"  id="checkout-button">Proceed</button>
            </div>
          </div>

  </section>
  {% csrf_token %}
</body>
  <script type="text/javascript">
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("pk_test_51IqKbySADauyMaoOtapXqTTr0TccaOhUIaC7gRjbVQLWEVJ2i0eauSBT4x9YOF5djlXZHLYfgZXWPhcDmguR25WJ006Cu5CMXm");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
      fetch("{% url 'accounts:create-checkout-session' id %}", {
        method: "POST",
        headers:{
            'X-CSRFToken':csrftoken
        }
      })
        .then(function (response) {
          return response.json();
        })
        .then(function (session) {
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });
  </script>
</html>

{% endblock %}  

accounts/templates/accounts/log_in.html
{% extends 'accounts/components/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="header3  cid-rbb39CwPur" id="header3-6" data-sortbtn="btn-primary">
    <div class="mbr-overlay" style="opacity: 0.2;">
    </div>
    <div class="container  d-flex justify-content-center" style="padding: 143px;">
    <div class="row my-auto "  style="height: 400px; width:45%;">
        <form method="post" id="myform">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="row d-flex justify-content-around">
                <div class="navbar-buttons mbr-section-btn">
                    <a onclick="document.getElementById('myform').submit()" class="btn btn-sm btn-info display-4" >Login</a>
                </div>
                <div class="navbar-buttons mbr-section-btn">
                    <a class="btn btn-sm btn-info display-4" href="{% url 'accounts:sign-up' %}">New User?</a>
                </div>
            </div>
        </form>
    </div>
</div>
</div>

{% endblock %}

accounts/templates/accounts/my_orders.html
{% extends 'accounts/components/base.html' %}


{% block content %}
<section class="mbr-gallery cid-rbaMy1tJOl" once="shops" id="shop6-2" data-sortbtn="btn-primary">
    <div>
        <div class="mbr-shop" shop__showsidebar="">

            <div class="row col-md-12">
                <div class="col-xl-2 sidebar">
                    {% include 'accounts/components/sidebar.html' %}
                </div>
                <div class="col-xl-1"></div>
                <div class="col-xl-9">
                <div class="wrapper-shop-items ">
                    {% for message in messages %}
                                        <div class="alert alert-success alert-dismissible" role="alert">
                                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                          </button>
                                          {{ message }}
                                        </div>
                                      {% endfor %}
                    <div class="table-responsive">
                        <table class="table no-wrap">
                            <thead>
                                <tr>
                                    <th class="border-top-0">No.</th>
                                    <th class="border-top-0">Date and Time</th>
                                    <th class="border-top-0">Product </th>
                                    <th class="border-top-0">Address</th>
                                    <th class="border-top-0">Payment Status</th>
                                    <th class="border-top-0">Order </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for order in orders %}
                                <tr>
                                    <td>
                                        <num>
                                    </td>
                                    <td class="txt-oflo">{{order.date}}</td>
                                    <td>Name: {{order.cake_list.name}} <br> Price: ₹ {{order.cake_list.price}} <br>
                                        <img src="/media/{{order.cake_list.image}}" style="height: 150px; width:175px">
                                    </td>
                                    <td class="txt-oflo">{{order.first_name}} &nbsp; {{order.last_name}} <br>
                                        {{order.house_name}}<br>{{order.location}}<br>Pin:{{order.pin}} <br> Phone:
                                        {{order.phone}} <br> Email: {{order.email}}
                                    </td>
                                    {% if order.status == 'Pending' %}
                                    <td><span class="text-info" style="font-weight: bolder;font-size: larger;">₹ {{order.cake_list.price}} <br> {{order.status}}</span></td>
                                    {% else %}
                                    <td><span  style="font-weight: bolder;font-size: larger;color: green;">₹ {{order.cake_list.price}} <br> {{order.status}}</span></td>
                                    {% endif %}
                                    {% if order.order_status == 'True' %}
                                    <td><a class="btn btn-danger" href="{% url 'accounts:cancel-order' order.id %}">Cancel Order</a></td>
                                    {% else %}
                                    <td><span  style="font-weight: bolder;font-size: larger;color:red;">Order Cancelled</td>
                                    {% endif %}
                        
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            </div>

        </div>
    </div>

</section>

{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends 'accounts/components/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<div class="header3  cid-rbb39CwPur" id="header3-6" data-sortbtn="btn-primary">
    <div class="mbr-overlay" style="opacity: 0.2;">
    </div>
    <div class="container  d-flex justify-content-center" style="padding: 148px;">
        <div class="row centered-form">
            {% if messages  %}
            <div class="col-12"  >
            {% else %}
            <div class="col-12" style="height: 386px;">
            {% endif %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                    </div>
                    <div class="panel-body">
                        {% for message in messages %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                          {{ message }}
                        </div>
                      {% endfor %}
                        <form id='myform' method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div id="div_id_firstname" class="form-group"> <label for="id_firstname" class=" requiredField">
                                        </label>
                                        <div class=""> <input type="text" placeholder="First name" name="first_name" maxlength="150"
                                                autocapitalize="none" autocomplete="first_name" autofocus=""
                                                class="textinput textInput form-control" required="" id="id_first_name">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <div id="div_id_lastname" class="form-group"> <label for="id_lastname" class=" requiredField">
                                            </label>
                                            <div class=""> <input type="text" placeholder="Last name" name="last_name" maxlength="150"
                                                    autocapitalize="none" autocomplete="last_name" autofocus=""
                                                    class="textinput textInput form-control" required="" id="id_last_name">
                                            </div>
                                        </div>
                            
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div id="div_id_username" class="form-group"> <label for="id_username"
                                        class=" requiredField">
                                       </label>
                                    <div class=""> <input type="text" placeholder="Username" name="username"
                                            maxlength="150" autocapitalize="none" autocomplete="username" autofocus=""
                                            class="textinput textInput form-control" required="" id="id_username">
                                        <small id="hint_id_username" class="form-text text-muted">
                                    </div>
                                </div>

                            </div>
                            <div class="form-group">
                                <div id="div_id_email" class="form-group"> <label for="id_email"
                                        class=" requiredField">
                                       </label>
                                    <div class=""> <input type="email" placeholder="Email Address" name="email"
                                            maxlength="150" autocapitalize="none" autocomplete="email" autofocus=""
                                            class="textinput textInput form-control" required="" id="id_email">
                                        <small id="hint_id_email" class="form-text text-muted">
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <div id="div_id_password1" class="form-group"> <label for="id_password1"
                                                class=" requiredField">
                                            </label>
                                            <div class=""> <input type="password" placeholder="Password"
                                                    name="password1" autocomplete="new-password"
                                                    class="textinput textInput form-control" required=""
                                                    id="id_password1">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-6 col-sm-6 col-md-6">
                                    <div class="form-group">
                                        <div id="div_id_password2" class="form-group"> <label for="id_password2"
                                                class=" requiredField">
                                            </label>
                                            <div class=""> <input type="password" placeholder="Confirm Password"
                                                    name="password2" autocomplete="new-password"
                                                    class="textinput textInput form-control" required=""
                                                    id="id_password2">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row d-flex justify-content-around">
                                <div class="navbar-buttons mbr-section-btn">
                                    <a onclick="document.getElementById('myform').submit()"
                                        class="btn btn-sm btn-info display-4">Sign Up</a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


{% endblock %}