accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from products.views import CreateCheckoutSessionView

app_name="accounts"

urlpatterns = [
    path('',views.indexpage,name="indexpage"),
    path('homepage/',views.homepage,name="homepage"),
    path('signup/',views.sign_up,name="sign-up"),
    path('login/',views.log_in,name="log-in"),
    path('logout/',views.log_out,name="log-out"),


    path('category/<str:category_name>',views.category_filter,name='filter'),
    path('checkout/<int:id>',views.checkout,name='checkout'),
    path('myorders/',views.my_orders,name="my-orders"),
    path('cancel-order/<int:id>',views.cancel_order,name="cancel-order"),
    path('prediction/',views.prediction,name="prediction"),
    path('analyze',views.analyze,name="analyze"),
    path('messages/',views.messages,name="messages"),

    path('landing-page/',views.landing_page,name="landing-page"),
    path('create-checkout-session/<int:id>',CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('payment-successfull/',views.payment_successfull,name='payment-successfull'),
    path('payment-cancelled/',views.payment_cancelled,name='payment-cancelled')

    

]

admin/urls.py
from django.contrib import admin
from django.urls import path
from .views import admin_views,product_views

app_name="admin"

urlpatterns = [
    path('',admin_views.dashboard,name='dashboard'),
    path('update',admin_views.update_profile,name='update-profile'),
    path('user-list',admin_views.user_list,name='user-list'),
    
    path('add-cake',product_views.add_cake,name='add-cake'),
    path('update-cake/<int:id>',product_views.update_cake,name='update-cake'),
    path('delete-cake/<int:id>',product_views.delete_cake,name='delete-cake')

]

cakebakery/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('',include('accounts.urls')),
    path('admin/',include('admin.urls')),
   

]   + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length = 32)
    first_name = forms.CharField(max_length=32)
    last_name=forms.CharField(max_length=32)
    email=forms.EmailField(max_length=64)
    password1=forms.CharField()
    password2=forms.CharField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email',)

accounts/views.py
from django.shortcuts import render,reverse,redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages as mssg
from products.models import cake_list,orders,messages
from .forms import SignUpForm
from products.forms import make_order_form,message_form
import pandas as pd   
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


# Create your views here.

def indexpage(request):
    context = dict()
    context['title'] = 'indexpage'
    return render(request,'accounts/index.html',context)

def homepage(request):
    context = dict()
    items = cake_list.objects.all()
    context['items'] = items
    return render(request,'accounts/homepage.html',context)

def category_filter(request,category_name):
    context = dict()
    items = cake_list.objects.filter(category = category_name)
    context['items'] = items
    return render(request,'accounts/homepage.html',context)

def sign_up(request):
    form = SignUpForm(request.POST or None)
    context= dict()
    context["form"] = form
    if request.method == "POST":
        if form.is_valid(): 
            user=form.save()
            login(request,user)      
            return redirect(reverse('accounts:homepage'))
        else:
            mssg.info(request,form.errors)
            return render(request,'accounts/sign_up.html',context)
    return render(request,'accounts/sign_up.html',context)

def log_in(request):
    form = AuthenticationForm(request, data=request.POST)
    context= dict()
    context["form"] = form
    if request.method == "POST":
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username = username,password=password)
            login(request,user)  
            if user.is_superuser:
                return redirect(reverse('admin:dashboard'))
            if user:    
                return redirect(reverse('accounts:homepage'))
        else:
            return render(request,'accounts/log_in.html',context)    
    return render(request,'accounts/log_in.html',context)

def log_out(request):
    logout(request)
    return redirect(reverse('accounts:log-in'))

def my_orders(request):
    context = dict()
    user = request.user
    myorders = orders.objects.filter(user_id = user.id).order_by('-date')
    context['orders'] = myorders
    return render(request,'accounts/my_orders.html',context)

def cancel_order(request,id):
    order = orders.objects.get(id = id)
    order.order_status = 'Cancelled'
    order.save()
    mssg.info(request,'Order cancelled successfully. Refund will be credited to your bank account within 3-4 working days')
    return redirect(reverse('accounts:my-orders'))

def prediction(request):
    return render(request, 'accounts/prediction.html')

def analyze(request):
    crop = pd.read_csv("dataset/Crop_recommendation.csv")

    # remove duplicate values
    crop.drop_duplicates()

    # handle null values in dataset
    attr=["N","P","K","temperature","humidity","rainfall","label"]
    if crop.isna().any().sum() !=0:
        for i in range(len(attr)):
            crop[atrr[i]].fillna(0.0, inplace = True)

    #Remove unwanted parts from strings in a column 
    crop.columns = crop.columns.str.replace(' ', '') 

    # we have given 7 features to the algorithm
    features = crop[['N', 'P','K','temperature', 'humidity', 'ph', 'rainfall']]

    # dependent variable is crop
    target = crop['label']

    # our model will contain training and testing data
    x_train, x_test, y_train, y_test = train_test_split(features,target,test_size = 0.2,random_state =2)
    
    # here n_estimators is The number of trees in the forest.
    # random_state is for controlling  the randomness of the bootstrapping
    RF = RandomForestClassifier(n_estimators=20, random_state=0)

    # we'll use rf.fit to build a forest of trees from the training set (X, y).
    RF.fit(x_train,y_train)
    # at this stage our algorithm is trained and ready to use
    
    # take values from user
    N = request.POST.get('nitrogen', 'default')
    P = request.POST.get('phosphorous', 'default')
    K = request.POST.get('potassium', 'default')
    temp = request.POST.get('temperature', 'default')
    humidity = request.POST.get('humidity', 'default')
    ph =request.POST.get('ph', 'default')
    rainfall = request.POST.get('rainfall', 'default')

    # make a list of user input
    userInput = [N, P, K, temp, humidity, ph, rainfall]
    
    # use trained model to predict the data based on user input
    result = RF.predict([userInput])[0]

    # display  result to the user
    params = {'purpose':'Predicted Crop: ', 'analyzed_text': result.upper()}
    return render(request, 'accounts/analyze.html', params)    
    

def messages(request):
    context = dict()
    form = message_form(request.POST or None)
    context['form'] = form
    if request.method == "POST":
        if form.is_valid: 
            order=form.save()
            mssg.info(request,'Thank you for filling the form. Will get back to you soon')
    return render(request,'accounts/messages.html',context)

def checkout(request,id):
    context = dict()
    customer=request.user
    form = make_order_form(request.POST or None)
    context['customer'] = customer
    context['form'] = form
    if request.method == "POST":
        if form.is_valid: 
            order=form.save(commit = False)    
            order.user_id = customer.id
            order.cake_list_id = id
            order = order.save()
            context['id'] = id
            return render(request,'accounts/landingpage.html',context)
    return render(request,'accounts/delivery_details.html',context)

def landing_page(request):
    return render(request,'accounts/landingpage.html')

def payment_cancelled(request):
    cancel_order = orders.objects.latest('id')
    if cancel_order.status == 'Pending':
        cancel_order.delete()
    return redirect(reverse('accounts:homepage'))

def payment_successfull(request):
    success_order = orders.objects.latest('id')
    success_order.status = 'Success'
    success_order.save()
    return redirect(reverse('accounts:my-orders'))

accounts/templates/accounts/components/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Site made with Mobirise Website Builder v4.8.8, https://mobirise.com -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v4.8.8, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="{% static 'assets/images/logo.jpg' %}" type="image/x-icon">
    <meta name="description" content="">
    <title>Geo Flora Prediction</title>
    <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/socicon/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/gallery/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
    



</head>

<body>
    <section class="menu cid-rbb1P7Oggj" once="menu" id="menu1-5" data-sortbtn="btn-primary">




        <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
            <div class="navbar-brand">

                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-2"
                        href="{% url 'accounts:indexpage' %}"  > Geo Flora Prediction
                      </a>

                </span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {% if title != 'indexpage' %}
                {% if user.username %}
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4" href="#">
                            Hi {{user.first_name}}</a>
                    </li>
                </ul>

                <div class="navbar-buttons mbr-section-btn"><a class="btn btn-sm btn-info display-4" href="{% url 'accounts:log-out' %}">
                        Logout</a></div>
                {% else %}
                <div class="navbar-buttons mbr-section-btn"><a class="btn btn-sm btn-info display-4" href="{% url 'accounts:log-in' %}">
                    Sign In</a></div>

                <div class="navbar-buttons mbr-section-btn"><a class="btn btn-sm btn-info display-4" href="{% url 'accounts:sign-up' %}">
                        New User?</a></div>
                {% endif %}
                {% endif %}
            </div>
        </nav>
    </section>
 


    {% block content %}

    {% endblock %}
  



  <script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/popper/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
  <script src="{% static 'assets/touchswipe/jquery.touch-swipe.min.js' %}"></script>
  <script src="{% static 'assets/mobirise-shop/script.js' %}"></script>
  <script src="{% static 'assets/dropdown/js/script.min.js' %}"></script>
  <script src="{% static 'assets/theme/js/script.js' %}"></script>
  <script src="{% static 'assets/gallery/player.min.js' %}"></script>
  <script src="{% static 'assets/gallery/script.js' %}"></script>

</body>

</html>

accounts/templates/accounts/components/sidebar.html
{% load static %}


<div class="sidebar-background"></div>
<div class="sidebar-block container ">
    <h4 class="sidebar-title mbr-fonts-style mbr-text display-4" style="font-weight:600; font-size: larger;">Welcome  {{user.first_name}}&nbsp;{{user.last_name}}</h4>
    <div class=" mbr-section-btn pt-5" ><a class="btn btn-sm btn-info" href="{% url 'accounts:prediction' %}">Prediction</a></div>
    <div class=" mbr-section-btn pt-5" ><a class="btn btn-sm btn-info" href="{% url 'accounts:my-orders' %}">My Orders</a></div>
    <div class=" mbr-section-btn " ><a class="btn btn-sm btn-info" href="{% url 'accounts:messages' %}">Feedback</a>
    </div>
    <div class=" mbr-section-btn">
         <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle btn btn-sm btn-info" >Categories</a>
    <ul class="collapse list-unstyled" id="pageSubmenu">
        <li >
            <a  class=" btn btn-sm btn-success"  href="{% url 'accounts:homepage' %}">All</a>
        </li>
        <li>
            <a  class=" btn btn-sm btn-success" href="{% url 'accounts:filter' 'Popular flavours' %}">Seed</a>
        </li>
        <li>
            <a class=" btn btn-sm btn-success" href="{% url 'accounts:filter' 'Design Cakes' %}">Fertilizer</a>
        </li>
        <li>
            <a class=" btn btn-sm btn-success" href="{% url 'accounts:filter' 'Jar Cakes' %}">Insecticide</a>
        </li>
        <li>
            <a class=" btn btn-sm btn-success" href="{% url 'accounts:filter' 'Brownies' %}">Farm Equipment</a>
        </li>
    </ul>
    </div>
   
</div>